server:
  port: 9001
spring:
  kafka:
    bootstrap-servers: kafka:9092
  data:
    mongodb:
      uri:  mongodb+srv://oliveraluis11:oliveraluis11@cluster0.iflkfqp.mongodb.net/dw-wallet-service?retryWrites=true&w=majority
