server:
  port: 9002
spring:
  kafka:
    bootstrap-server: localhost:9092
  datasource:
    url: jdbc:postgresql://containers-us-west-170.railway.app:7284/railway
    username: postgres
    password: QKjed8CJCAq8lZI7xvLm
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
    locations: classpath:db-migration
